### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by pbugnion** [voila-gallery/gallery#10]
There's still a few installation niggles:
- [x] the `gallery.yaml` file needs to be manually copied into site-packages. The best way to solve this might be through package data? Addressed in PR #13 .
- [x] the installation of the `tljh-voila-gallery` package does not currently install the package. Addressed in PR #9.
- [ ] dockerspawner is only installed after hub has started running. This requires running `sudo systemctl restart jupyterhub` after dockerspawner has been installed.
- [x] the build-images script still needs PyYaml -- this should be removed in favour of ruamel.yaml. Addressed in PR #12 .
- [ ] we could create the build-images systemd service as a post-install step.

As of now, running the following commands brings up a fully working system:

```
git clone https://github.com/jupyterhub/the-littlest-jupyterhub.git
git clone https://github.com/voila-gallery/gallery.git
cd ~/the-littlest-jupyterhub/
sudo python3 bootstrap/bootstrap.py --plugin /home/ubuntu/gallery/tljh-voila-gallery/
sudo systemctl restart jupyterhub  # restart with dockerspawner
sudo /opt/tljh/hub/bin/build-gallery-images
```

**Comment by yuvipanda** [comment]
once #17 is merged you don't need the restart anymore.

**Comment by jtpio** [comment]
The two remaining points (restart and build-images systemd service) have now been added.
